services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todoapp_dev
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
